# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-06-07 10:43:43
"""
import arcpy
from sys import argv

def AddCalculateFields(GamaWellsRanThroughDEMclp="GamaWellsRanThroughDEMclp"):  # Add Calculate Fields

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: Add Fields (multiple) (Add Fields (multiple)) (management)
    CentralBasinMo_InterpolateSh = arcpy.management.AddFields(in_table=GamaWellsRanThroughDEMclp, field_description=[["ZinFeet", "DOUBLE", "", "", "", ""], ["ElevationBottomofWellFeet", "DOUBLE", "", "", "", ""], ["BottomCalcMethod", "TEXT", "", "255", "", ""]], template=[])[0]

    # Process: Calculate Z in Feet (Calculate Field) (management)
    CentralBasinMo_InterpolateSh_2_ = arcpy.management.CalculateField(in_table=CentralBasinMo_InterpolateSh, field="ZinFeet", expression="$feature.Z * 3.28", expression_type="ARCADE", code_block="", field_type="DOUBLE", enforce_domains="NO_ENFORCE_DOMAINS")[0]

    # Process: Select Rows with Screen Depths (Select Layer By Attribute) (management)
    TESTINGSAMPLE_4_, Count = arcpy.management.SelectLayerByAttribute(in_layer_or_view=CentralBasinMo_InterpolateSh_2_, selection_type="NEW_SELECTION", where_clause="GM_BOTTOM_DEPTH_OF_SCREEN_FT IS NOT NULL", invert_where_clause="")

    # Process: Calculate Depth (Calculate Field) (management)
    CentralBasinMo_InterpolateSh_4_ = arcpy.management.CalculateField(in_table=TESTINGSAMPLE_4_, field="ElevationBottomofWellFeet", expression="$feature.ZinFeet - $feature.GM_BOTTOM_DEPTH_OF_SCREEN_FT", expression_type="ARCADE", code_block="", field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]

    # Process: Add Text (Calculate Field) (management)
    gama_all_valid_DEM_4_ = arcpy.management.CalculateField(in_table=CentralBasinMo_InterpolateSh_4_, field="BottomCalcMethod", expression="\"Screen Depth\"", expression_type="ARCADE", code_block="", field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]

    # Process: Select Rows with Total Depths (Select Layer By Attribute) (management)
    TESTINGSAMPLE_2_, Count_2_ = arcpy.management.SelectLayerByAttribute(in_layer_or_view=gama_all_valid_DEM_4_, selection_type="NEW_SELECTION", where_clause="GM_BOTTOM_DEPTH_OF_SCREEN_FT IS NULL And GM_WELL_DEPTH_FT IS NOT NULL", invert_where_clause="")

    # Process: Calculate Depth (2) (Calculate Field) (management)
    gama_all_valid_DEM_3_ = arcpy.management.CalculateField(in_table=TESTINGSAMPLE_2_, field="ElevationBottomofWellFeet", expression="$feature.ZinFeet - $feature.GM_WELL_DEPTH_FT", expression_type="ARCADE", code_block="", field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]

    # Process: Add Text (2) (Calculate Field) (management)
    gama_all_valid_DEM_2_ = arcpy.management.CalculateField(in_table=gama_all_valid_DEM_3_, field="BottomCalcMethod", expression="\"Total Well Depth\"", expression_type="ARCADE", code_block="", field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]

    # Process: Add Global IDs (Add Global IDs) (management)
    Updated_Datasets = arcpy.management.AddGlobalIDs(in_datasets=[gama_all_valid_DEM_2_])[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\Kat Plank\OneDrive - Innovate, Inc!\Documents\R9 Projects\SFD_23_04554_CentralBasin3DGISSupport\ArcProProjects\Testing\Default.gdb", workspace=r"C:\Users\Kat Plank\OneDrive - Innovate, Inc!\Documents\R9 Projects\SFD_23_04554_CentralBasin3DGISSupport\ArcProProjects\Testing\Default.gdb"):
        AddCalculateFields(*argv[1:])
