# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-06-07 10:44:24
"""
import arcpy
from sys import argv

def ImportGAMAbyAll(Central_Basin_Boundary="C:\\Users\\Kat Plank\\OneDrive - Innovate, Inc!\\Documents\\R9 Projects\\SFD_23_04554_CentralBasin3DGISSupport\\ArcProProjects\\Testing\\Sites.gdb\\CentralBasinBoundary", _name_PairwiseClip="C:\\Users\\Kat Plank\\OneDrive - Innovate, Inc!\\Documents\\R9 Projects\\SFD_23_04554_CentralBasin3DGISSupport\\ArcProProjects\\Testing\\Default.gdb\\%name%__PairwiseClip", gama_ddw_losangeles_v2_txt="C:\\Users\\Kat Plank\\OneDrive - Innovate, Inc!\\Documents\\R9 Projects\\SFD_23_04554_CentralBasin3DGISSupport\\OriginalData\\DataUpdate_20230420\\gama_ddw_losangeles_v2.txt"):  # Import GAMA by All

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")

    # Process: XY Table To Point (XY Table To Point) (management)
    XY_Data = "C:\\Users\\Kat Plank\\OneDrive - Innovate, Inc!\\Documents\\R9 Projects\\SFD_23_04554_CentralBasin3DGISSupport\\ArcProProjects\\Testing\\Default.gdb\\%name%"
    arcpy.management.XYTableToPoint(in_table=gama_ddw_losangeles_v2_txt, out_feature_class=XY_Data, x_field="GM_LONGITUDE", y_field="GM_LATITUDE", z_field="", coordinate_system="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision")

    # Process: Pairwise Clip (Pairwise Clip) (analysis)
    with arcpy.EnvManager(outputZFlag="Disabled"):
        arcpy.analysis.PairwiseClip(in_features=XY_Data, clip_features=Central_Basin_Boundary, out_feature_class=_name_PairwiseClip, cluster_tolerance="")

    # Process: Delete (Delete) (management)
    if _name_PairwiseClip:
        Delete_Succeeded = arcpy.management.Delete(in_data=[XY_Data], data_type="")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\Kat Plank\OneDrive - Innovate, Inc!\Documents\R9 Projects\SFD_23_04554_CentralBasin3DGISSupport\ArcProProjects\Testing\Default.gdb", workspace=r"C:\Users\Kat Plank\OneDrive - Innovate, Inc!\Documents\R9 Projects\SFD_23_04554_CentralBasin3DGISSupport\ArcProProjects\Testing\Default.gdb"):
        ImportGAMAbyAll(*argv[1:])
