# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-06-07 10:45:08
"""
import arcpy
from sys import argv

def RunThroughDEM(gama_all_losangeles_v3_validdepths="C:\\Users\\Kat Plank\\OneDrive - Innovate, Inc!\\Documents\\R9 Projects\\SFD_23_04554_CentralBasin3DGISSupport\\ArcProProjects\\Testing\\UpdateData_20230201.gdb\\gama_all_losangeles_v3_validdepths", CentralBasinMosaicDEM="CentralBasinMosaicDEM", CentralBasinMo_InterpolateSh="C:\\Users\\Kat Plank\\OneDrive - Innovate, Inc!\\Documents\\R9 Projects\\SFD_23_04554_CentralBasin3DGISSupport\\ArcProProjects\\Testing\\UpdateData_20230201.gdb\\gama_all_valid_DEM"):  # Run Through DEM

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: Interpolate Shape (Interpolate Shape) (sa)
    gama_all_valid_DEM = "C:\\Users\\Kat Plank\\OneDrive - Innovate, Inc!\\Documents\\R9 Projects\\SFD_23_04554_CentralBasin3DGISSupport\\ArcProProjects\\Testing\\UpdateData_20230201.gdb\\gama_all_valid_DEM"
    arcpy.sa.InterpolateShape(in_surface=CentralBasinMosaicDEM, in_feature_class=gama_all_losangeles_v3_validdepths, out_feature_class=gama_all_valid_DEM, sample_distance=None, z_factor=1, method="BILINEAR", vertices_only="DENSIFY", pyramid_level_resolution=0, preserve_features="EXCLUDE")
    .save(Interpolate_Shape)


    # Process: Add Z Information (Add Z Information) (3d)
    CentralBasinMo_InterpolateSh = arcpy.ddd.AddZInformation(in_feature_class=gama_all_valid_DEM, out_property=["Z"], noise_filtering="")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\Kat Plank\OneDrive - Innovate, Inc!\Documents\R9 Projects\SFD_23_04554_CentralBasin3DGISSupport\ArcProProjects\Testing\Default.gdb", workspace=r"C:\Users\Kat Plank\OneDrive - Innovate, Inc!\Documents\R9 Projects\SFD_23_04554_CentralBasin3DGISSupport\ArcProProjects\Testing\Default.gdb"):
        RunThroughDEM(*argv[1:])
