on:
  push:
    branches:
      - master


name: Build App
jobs:
  build:
    uses: ./.github/workflows/build.yml

  set_destination:
    runs-on: ubuntu-latest
    environment: NEW_ER_CLOUD
    needs: build
    outputs:
        destination: ${{ steps.set_destination.outputs.destination }}
    steps:
      - name: Set Destination
        id: set_destination
        run: |
          echo "destination=\\\${{ vars.WEB_HOST }}\R9Apps\centralbasin" >> $GITHUB_OUTPUT

  deploy:
    needs: set_destination
    uses: ./.github/workflows/deploy.yml
    with:
      destination: ${{ needs.set_destination.outputs.destination }}
