on:
  push:
    branches:
      - master

name: Build App
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        run: |
          npm ci
          npm run build
      - name: Push Build to Releases
        uses: actions/upload-artifact@v2
        with:
            name: build
            path: "dist/*"


  deploy:
    needs: build
    runs-on: self-hosted
    environment: NEW_ER_CLOUD
    steps:
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist
      - name: Deploy to Server
        run: |
          echo "Deploying to server"
          if (Test-Path \\${{ vars.WEB_HOST }}\R9Apps\staging\centralbasin-test) {
            Remove-Item -Recurse -Force \\${{ vars.WEB_HOST }}\R9Apps\staging\centralbasin-test
          }
          Copy-Item -Source ${{GITHUB_WORKSPACE}}\* -Destination \\${{ vars.WEB_HOST }}\R9Apps\staging\centralbasin-test -Recurse -Force
